# Xamarin.iOS
# Build a Xamarin.iOS project.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

pool:
  vmImage: 'macOS 10.13'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/Xamarin.Forms.SKMaps.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
    
- task: XamariniOS@2
  inputs:
    solutionFile: '**/Xamarin.Forms.SKMaps.csproj'
    configuration: '$(buildConfiguration)'
    packageApp: false
    buildForSimulator: false
    
- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: '**/Xamarin.Forms.SKMaps.csproj'
    
- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: '<Name of the NuGet service connection>'
    versioningScheme: byEnvVar
    versionEnvVar: Version
