# Xamarin.iOS
# Build a Xamarin.iOS project.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

pool:
  vmImage: 'macOS 10.13'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: '**/Xamarin.Forms.SKMaps.csproj'